#debug mode, set TRUE if you want debug messages
debugmode: false

#total required time (minutes)
totaltime: 246

# default color normal text in messages
default-color: "&r&7"

# The following placeholders are exclusive to an event
# %invplugin_most_recent_invited_rewarded%------> award event
# %invplugin_most_recent_invited_selected%------> select event
# %invplugin_most_recent_invited_locked%--------> locked event
# %invplugin_most_recent_invited_completed%-----> completed event

# mesages
invite-stats:
  - "------[ &6&lInvite Rewards&r ]------"
  - "Player: &f%invplugin_self%"
  - "Inviter: &f%invplugin_inviter%"
  - "Locked: %invplugin_locked%"
  - "Progress: &3%invplugin_progress%"
  - "Invited: %invplugin_invited_count%"

invite-list-structure:
  - " - &f%invplugin_self% %invplugin_brief_stats%"

login-message:
  new:
    - "Who invited you to the server? Use &b/%invplugin_invite_selection_command% &bplayer"
  old:
    not-invited:
      - "Who invited you to the server? Use &b/%invplugin_invite_selection_command% &bplayer"
    invited:
      not-locked-but-completed:
        - "Looks like you have played on the server for a while, but you haven't selected your inviter"
        - "To do so, use &b/%invplugin_invite_selection_command%"
      not-completed:
        - "Play for &d%invplugin_minutes_left% more minutes so &d%invplugin_inviter% can get a reward"


# when both the invited has locked in inviter and has completed the requirements
award-message:
  invited:
    - ""
    - "     &d%invplugin_inviter% will now receive a reward%"
    - ""
  inviter:
    - ""
    - "     &a&l&oCONGRATULATIONS!"
    - ""
    - "     You invited &b%invplugin_most_recent_invited_rewarded%, which means you get a reward!"
    - ""

# fired when invited types /inviteconfirm
locked-message:
  invited:
    - ""
    - "     You locked in &b%invplugin_inviter% as your inviter"
    - ""
  inviter:
    - ""
    - "     &d%invplugin_most_recent_invited_locked% has selected you as their inviter"
    - ""
    - "     When &d%invplugin_most_recent_invited_locked% has played for &d%invplugin_time_total%, you will get a reward!"
    - ""

# fired when invited completes requirements
completed-message:
  invited:
    - ""
    - "     &3&l&oCONGRATULATIONS!"
    - ""
    - "     You played on the server for &d%invplugin_time_required%"
    - ""
  inviter: []

# fired when invited selects inviter
selected-message:
  invited:
    - ""
    - "     You selected &d%invplugin_inviter%&7 to be your inviter"
    - ""
    - "     Type &d/%invplugin_invited_confirm_command% to confirm your selection"
    - ""
  inviter: []