#debug mode, set TRUE if you want debug messages
debugmode: false

#total required time (minutes)
totaltime: 1

#minimum number of logins
logins: 4

#minimum time spent on each login for login to count
login-min: 15

#