#debug mode, set TRUE if you want debug messages
debugmode: false

#total required time (minutes)
totaltime: 90

#minimum number of logins
logins: 4

#minimum time spent on each login for login to count
login-min: 15

default-color: "&r&7"

#mesages
invite-stats:
  - "------[ &6&lInvite Rewards ]------"
  - "Player: &f%invplugin_self%"
  - "Inviter: &f%invplugin_inviter%"
  - "Locked: %invplugin_locked%"
  - "Progress: &3%invplugin_progress%"
  - "Invited: %invplugin_invited_count%"

invite-list-structure:
  - " - &d%invplugin_self%: %invplugin_brief_stats%"

login-message:
  new:
    - "Who invited you to the server? Use &b/%invplugin_invite_selection_command% &bplayer"
  old:
    not-invited:
      - "Who invited you to the server? Use &b/%invplugin_invite_selection_command% &bplayer"
    invited:
      not-locked-but-completed:
        - "Looks like you have played on the server for a while, but you haven't selected your inviter"
        - "To do so, use &b/%invplugin_invite_selection_command%"
      not-completed:
        - "Play for &d%invplugin_minutes_left% more minutes so &d%invplugin_inviter% can get a reward"

award-message:
  invited:
    - ""
    - "     &d%invplugin_inviter% will now receive a reward%"
    - ""
  inviter:
    - ""
    - "     &a&l&oCONGRATULATIONS!"
    - "     You invited &b%invplugin_most_recent_invited_completion%, which means you get a reward!"
    - ""

locked-message:
  invited:
    - ""
    - "     You locked in &b%invplugin_inviter% as your inviter"
    - ""
  inviter:
    - ""
    - "     &d%invplugin_most_recent_invited_locked% has selected you as their inviter"
    - "     When &d%invplugin_most_recent_invited_locked% has played for &d%invplugin_time_total%, you will get a reward!"
    - ""

completed-message:
  invited:
    - "&3&l&oCONGRATULATIONS!"
    - "You played on the server for &d%invplugin_time_required%"
  inviter: []

selected-message:
  invited:
    - ""
    - "     You selected &d%invplugin_inviter%&7 to be your inviter"
    - ""
    - "     Type &d/%invplugin_confirm_command% to confirm your selection"
    - ""
  inviter: []